language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO_SETTINGS_MODULE=haste.settings
install:
  - pip install -r requirements.txt
  - pre-commit install
  - pip install -U pytest
script:
  - pre-commit run --all-files
  - pytest
